---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vllm-hf-token
  namespace: vllm
spec:
  encryptedData:
    token: AgCujFYqXkP/c6cnZezRhHaQ9PrbBtqR2hNXidwGbxJKxLBurgWH1LxTlQuQTa2c7TdHT+OzvC0uTIIWKItY0IIZ3lxj/bQExZvgyVNPbHD5xNHlZ9FPbw4kF9dAZKqnLT1Gujw59694mpDpwgEJaIn7RiyiFC8IdDp4Xj1Ccfykf8OBYLcDEsbRjQksuDP8t/Jj3xYjfrPWB07Bd2YE6zS4z4Jf3UWl9ttcrm7bv09QBut5EXpc81Mq0uvE2dBTSS2bEhE/fuWrWLxIyAKQiWlbPZbz4BTPNFfeQeB63gcI8Z6GvcHmK4Pra8v1QpIO8yEd0As4AdblOtYmc4iuiov4X4uyi9bxVZU98ONWhn8jbrY1LVEWXjIyCbf3kVVLP9BoocJJlUguYuj8q73ae6SDxTRAYblQ99lofYIGsw1uCDTUcwYvL+rufuT1z74Of5va0Uynmsr/V5yqDcUBJ3pNj/OCIe3HEqZtyB9Nl+kLLe8lFeueYktNBlQrsUt53epMJMR/5/d5Lqq2VqpEEd9fT1LdRulrJXgi4rciW3ef1ie25eC5JfgJ5PfEKhHVkxXXIImtdBlw4vesUv0ifRsNNGNzUt7lNd3FiU9vf5ffTaED/QQegWVvKtJ9GqQCh22S+qZ6/7gVUJ5cJHNuTxVKeBLX/2+XkrSL2SKG9uLBpRppV0YnqXFkZDWmpGautETJTX0Dp/HjAZLuF7fY4Pap5vQ5vthhGnUGC6cztXhI/fIaFFx3
  template:
    metadata:
      name: vllm-hf-token
      namespace: vllm
    type: Opaque
