apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-migration
  namespace: vaultwarden
spec:
  template:
    spec:
      containers:
      - name: pgloader
        image: dimitri/pgloader:latest
        command:
        - /bin/sh
        - -c
        - |
          # Run pgloader
          pgloader --verbose --debug \
            --set "work_mem='128MB'" \
            --set "maintenance_work_mem='256MB'" \
            /sqlite/db.sqlite3 \
            postgresql://${USERNAME}:${PASSWORD}@vaultwarden-db-rw/vaultwarden
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: vaultwarden-db-creds
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: vaultwarden-db-creds
              key: password
        volumeMounts:
        - name: sqlite-data
          mountPath: /sqlite
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: sqlite-data
        persistentVolumeClaim:
          claimName: vaultwarden-pvc
