apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 2Gi
    storageClass: longhorn

  monitoring:
    enablePodMonitor: true

  bootstrap:
    recovery:
      source: "snapshot-bootstrap"

  externalClusters:
    - name: "snapshot-bootstrap"
      snapshot:
        name: "snap-ef46f0c8c3fc4ab3"
