apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.11.1
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            backupTarget: s3://nabelops-n8s@us-east-005/
            backupTargetSecret: longhorn-backup-secret
          ingress:
            enabled: true
            ingressClassName: tailscale
            host: longhorn
            annotations:
              tailscale.com/hostname: longhorn
            tls: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
