apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-site
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Nabelops/n8s.git
    targetRevision: HEAD
    path: apps/personal-site
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-site
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
