apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocket-id
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: https://auth.tailf95ba8.ts.net
spec:
  project: default
  source:
    repoURL: https://github.com/Nabelops/n8s.git
    targetRevision: HEAD
    path: apps/pocket-id
  destination:
    server: https://kubernetes.default.svc
    namespace: pocket-id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
