apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocm-gpu-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://rocm.github.io/gpu-operator
    targetRevision: v1.4.1
    chart: gpu-operator-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
