---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCFRwD2Ukj4AsvMH0MjG70O8I3PpSZiOc+qvZLw+PdZ+t5VCRPjvq2f10VI851HaxLsWB4r8UjdoNcCfYt+1+4TCeZIikB/m9lMD64z0MDl7eDo9en/5RCEjHSHnYFo5/wM+5FFQkvHBM0nLSokW02yjsUKhsZv39IfosU7WUJ2tvnZ1myo8aqfKFXdWd5gpBUQF3mbN+wxfvqAyqpwBQx3r4eci4GLv04fBrWWWkYL+Sk9J+9YdpGyyvToSolwD0gV2XXyMD4EffYK+CeaVZF9JrT1tBzORi6ofE5HzJKhNdutL61TxmDjgY3EbT+0MDyqg2riExN95FpfweuxWH0uaiANRRWYr0Dr8QPnwGpHyYI0MQWACi5ywrDA7bHHoLX5z4FUNYztZmAZge+UWYOe6YJ8Y21cJ/eFA71Ec7nkqe6EPD2kCSppKf/nzdin24u3WLvUcJWXzR9nVKLH0hPE4355kukg0Vf/EQ3ICJR8QCqObNxzPVXIdqSfxGLucitvEPB+hLzig7F1Vy6BP75Ny3TN5vIeiybdAnH8VdgmPgIsBMCf3z0ZTyzv1wX2LDVksBJepVv621a8nZ+PoojoC/6nL9gBdLGWpVJYmmCpKHIHX5XogXgrREk5FdSKsCbG/aHLiZHpVWyBhcxivQZCfuWaB6xbjE9aJCg59rV6pbEjs2Wma7SPVbhC7wDxx3b1scJMsBXBzLZxeEbeTw==
    admin-user: AgAMQ1BiSv2Hs57fBhD2hFDfeyRJvtZaN/vgDfLcCvK1ZFqOG8gsk+0tgw+fvKPa8w6+Ec59yCX8T2idagOOXvTGjhLB8/CKv6IlT1KrDshUHCFheyvnl5ZES/XxuXGncmAPmYMy4EdySnhTWoktPd8OA5+wPSDACqDlgTMe54mEPJACgKY4CdWlHH6gnQFUwxqC9+5ZTXmimCvv0xt3OkbAnSRjTPRlMirthuwUnFf7d5KGZjVuUg9N5BtqNbt3h0ajUSf1TT9G23SliWK1tcEDE4XHIEoRwXMR48bs5UMLTuDhY6EWFq9F+i3/Ukx92BFcD5dVLDBhIHN/7rXncvoX4J9HVC++wkmvTFPiCeaayRnWtgrexNm6qfx4c9TF9V30AAMasgN3Iuh6SmCNu0/FJ6Y1tXC59zvvq90PgrvOBdyeh3G/e+JNXadS652sR+JFJSJwH1faYsF/P7nqWf1TwuRyECej3SqWZXiu0W8AfwU/ixSvGyLtcy8Qb2uHgTR1eEIxcBCEL6xh27Wezs9GtK20XNAQ3tb+YWyTt3gn9KB+Z29H0ba5R5HyAyHJCBaKm9WKa+dCiSoifMfFJiy1Oa84rlLGaq6YJnlBmAA3aiOyvvlLfpi06gisf/cjgfa5d/cE2DYwi2mx6dZGCYc3O2mjCXOXSEEcCFTnEcIm7ulg5Hlfu+CEyOwv5ddCUO7l2nv+pBDv0YXEbMZEGrg=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
