---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-registry-secret
  namespace: personal-site
spec:
  encryptedData:
    .dockerconfigjson: AgAGHZf1xMLTM2pGeVv1P03psqS7+c3lepvetY8gIBfTJHNZRCbwuBggdcRcy77eMZgQnNkv4BCIrOsBACcP+UibK4+V9w0w74vpONhwXy2V7XfHoBb/5nilrgeZT5+LNFZ19UKe1MPQMENYUU3R4lbWJloq/84li0Pcb9PDeDiO/hjJ1Do7+WOxCHC2qBsvALkIqd5Fvr6ionpNi/mnoBofbTWfOkrLdfHtnvq6Dw/g8mWWpRr9pA6bIdnrZFvg7zbxPHhJ1r8/LFVJpsMFAQtZb14cV1xKsvcID6XsAOzvlvvKUhk5J4KHTqWRvL49oJbXUwQQFzZBEaL3df15jqxmH/PhLzObDlGzrNDJnYl+W4zzSAw7/SLti/xRqNe5ivuLHle1Xge/mFRxzZHWjDq81fWq16i+B+w2hRIJGPjKS1Cn0g1NF2fFkaFYZeynqo4zsSxNCuBUuhxLm1XJkvG9D08IUk10VtoWFI8aYll7EtUDQhj47x+EnsWzdhO/Y0dHUPkfegEBOo3RPv3uX4bqv2GX9bv1NIB5gZSP+FZtmrZ7HCR2IssoJe3OGUaN8BxEl6HIHg8Uxl2ZhjNnOS6/y6/H99IqIiav2KwZy4siN+b1hq32EVcwa6R9pqvRlyLGhJJUUItyLtirfUathZGOgBq5Zz7rBu+zK/pDcERI7TMrNsQE/d7l4JQ51vUM8eiHcBJ996X3T0HcNWFsvwE7drzqIrKKuX8SbAPeYzKJkooywjU8AkI0rQdyAtC0ct5gZccOV9WDhefJJ/fkMoE8PsSF/CPOJ/qIKOCtNeG0QwgpMRXgLElMfLHA/K+X//SCmmylYg3YUPxMrE080q5R4LL3/l5Uihz/yIU8ydAMmHfQ0wqdT4BbN1lX+Pp15KwTEYBMmp/ZlhhZUbfRVb07QlNlEp+0MH3wsX6jtDGzXgf0uHeXc36WyHD34UpELA==
  template:
    metadata:
      name: forgejo-registry-secret
      namespace: personal-site
    type: kubernetes.io/dockerconfigjson
