apiVersion: v1
kind: Service
metadata:
  name: personal-site-service
  namespace: personal-site
spec:
  selector:
    app: personal-site
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 4000
    - protocol: TCP
      name: https
      port: 443
      targetPort: 4000
