apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  # Increase connections for Redis-less Authentik
  postgresql:
    parameters:
      max_connections: "200"

  storage:
    size: 5Gi
    storageClass: local-path

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-creds
