apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://nabelops-n8s@us-east-005/"
  credentialSecret: "longhorn-backup-secret"
  pollInterval: "300s"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
  namespace: longhorn-system
value: "s3://nabelops-n8s@us-east-005/"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-secret
  namespace: longhorn-system
value: "longhorn-backup-secret"
