---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCo5xzq2ZW7v3kGvDotBDR+SpnQfYrV62fPc5xAg/m1QRFMPGMRL+uyOyd7mtdwyObeVvz18Pf0JQB3pw8I8j4gFPpdd72ezZf7sGpkie+NtXrZL33egrBBEAYDAyTTE33GpL/i4bZx2CQX913pY7rrTd1As/XtlSkBsiBn7Jqaam7TUpt1c51kCavgEzWcVEFCh+9KgKq5jV2X/SLMG+3FgY9ZlyASNQ0EcunoKsqyp3yn9nvCPG+voEOuUTWhwstJmYYiEf0u4XWwu1X46DbI3lqVAHAEVLNncOGKpXWp8qFkBDU27vbRQlCIU3b2EQOvI1xbOp5m1eiHXjYpkFpvIj016w9t4UWdO0sLqUhaSMG5d4vziZsvMBdDUkXd+9YKC2CPQ68lEVhUAWIeDX/n9zSNyNd52ov3rgmMx2FYgGi1M4UQvBM8AlL5Yt/lnAfE1LAR6K1wd8WG1M/C0COgC3eKm1g67/bXNrZufVaQqJziHpQa1G75ERCturMKiKUbJqvW5c5W+2BBfG0+61OxqH5phxNIn+ucxNWI/XBT8aTRmeFoUoHP2B2dXZ8vQ/7bGGwrVrom3Ngj71r6xMUdpFVmDeNgB4eCFw4QdIveLrhBxZFTCjQNfRd4udPthqYMZ7ROKFJ4C0fm8ZaUOnzo2HwF39kqUoalqpN8Iezilvh6jKXKto4/6Hrad4WoxfxT2ahiIxuTci3KkPXgUzTeHw==
    client_secret: AgBZEbD8yO/ChJ/yds3hpVdoWB4WPe1fPHv0LkKRv6CbTEYO+QCzwTPeoW9u+px5uWN0uMf4ADz1dXeFUS6qnBdg6SaqdlGXrDeg8BO3ErY1yXL7Du7LXVYnXqo82jjnUopGawC4bcCvOfVgZ9ifiSmK9bK5irRQHZhi8BcujK4ASKxCUoMKGXULpjpYEMqawBnLWqntyIz0MvoTByva83xLqeYghsfJh68Xay//2C46jMRu8KPvNW/+QuCwR2F5vYkvlvzeAS8lyNNMyYc9zx0L8K4EP5ow3e4Ab1rsjRjjUEcg2CKe+E2kuc3VqI+852QghixGVlt97XziwJL3TOLM06KXR9sXv03NJWqPfZ4eEnFUkedEtPis5KHjU0k7kfY7oWIH/Re4n6DHuP7PNx2ksCSjTinZcGlUF5BGQ7hLIG3SXzngg27SVv4N3+p3jdvARQFlzm//2CdAT6JbN1zkTeK2dqRSWDffwUZPshrqIdtZA7P14S84H13h3fPaNub5E5bkXbBWAK3p9hnKug6jpzwvX8jPNv0FS2egYTGewlTQsO+45Vp2EOCs2gNfZYwu5guZPxb01Cu/KsRo/d4mLKS2scMnYne25Q7sMqwbtnwQvDwxiUAFXrdfH89txjGd7NgvdNQP7RT0oB8EcyDiYgVYLqj8XYne1CJeLF6GZvrkBXWjffOS1518QF+S9LufAGfdzSU4jPuqNPGTTvqaGhuOmLI2aYYtkds0OJfi4N5rLB41Cv/aMNcXzAGWL3Jn8WR+LoQzoSzwr8rJ0bEw
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
