apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-config
  namespace: forgejo-runner
data:
  config.yml: |
    log:
      level: info
    runner:
      instance: http://forgejo-service.forgejo.svc.cluster.local
      file: /data/.runner
      labels:
        - "ubuntu-latest:docker://node:18-bullseye"
        - "ubuntu-22.04:docker://node:18-bullseye"
        - "ubuntu-20.04:docker://node:18-bullseye"
      capacity: 1
      envs:
        DOCKER_HOST: "tcp://localhost:2375"
    container:
      type: k8s
      network: ""
      privileged: false
      options: |
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      workdir_parent: ""
      valid_volumes: []
      docker_host: "tcp://localhost:2375"
      force_pull: false
