apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-config
  namespace: forgejo-runner
data:
  config.yml: |
    log:
      level: info
    runner:
      instance: http://forgejo-service.forgejo.svc.cluster.local
      file: /data/.runner
      labels:
        - "ubuntu-latest:docker://node:18-bullseye"
        - "ubuntu-22.04:docker://node:18-bullseye"
        - "ubuntu-20.04:docker://node:18-bullseye"
      capacity: 1
      # Move engine and kubernetes settings here
      engine: kubernetes
      kubernetes:
        namespace: forgejo-runner
        service_account_name: forgejo-runner
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
    container:
      workdir_parent: ""
      valid_volumes: []
      force_pull: false
