---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: runner-secret
  namespace: forgejo-runner
spec:
  encryptedData:
    token: AgCm+q2mhtKcpGbHE7lm5JHaD39O71x7IjXMz/YXKut2/l6Yda9qVe8bu7mBYWFDsCSx0jSf7y0sfjrWLSdDQSIU6G3gt6RAil30xvSSwcXtQUONyH8o/q3FG4lm20hDVFV/WfrHc5PSAfFP9YSQggXbZ3N5pne+1rvHUP3QsuORSh+O0redmJNdz4QwWMKXWV9GCDs983LHImGXwDst4tuJjJgyIExJMgV6+YB64JjQAjGi9RcmwwolpGvcF3lLUTMp4dzZCq4cdBpTx/PpdCrcjzYAQU5SyKecV92D+RAF+jlb/hQRBC7Ws8efXoroKrgvZ/ptCV8N7zmfulroiZfhOPjw3kngOQG15fQK3w2wCXInMpbfz/sGKK10IhIds+SxCdHBkEbp0YIDkdtRmtIB0STrC1fqW5DOAfDevC/Nfy4+J7kqUek/yv55n6ORLZJnUgViFlJ53c7b3bbv0BenFYJCqBrKGrRuOlyZDc6BSCYt3VZJaw3pYKg+BDqoUkhjX/iQDVkjB4IYYiDE1hvGHib4fEifms6ab5kN79PxH0km8bcCnSpJWgezE3Olcixyxenll9dKIr1GI06KORh1bBVCPXmuFGA7GUeRnP68kxkutfjjlnk+6mdt6Rc59JuQAlu83DVyv2C5N4U7LAMAlUheE7dtKfzmAeCjqhDU0b3ggJApbkvUeE4pqIIphcLVtuk8peZK1NBynMDO/+/TqkQjB3PCAogolGASQze75C7GLVQESR9CYAiZ
  template:
    metadata:
      name: runner-secret
      namespace: forgejo-runner
    type: Opaque
