---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAcIxlb4EdpFEAKMxt5wRoAu3tlVfg15IItzaqPvpwvs0BXcApfui4QfOTXQ5aJHX4Cl5gAP9ou3PepiARlDDcSLFRpeKpcOgs760UnGOQ6X0JHI7VyXXurEPk4cU8urCPkb2Dr1oe+w+xD805pg4FeQDMA9YydvduJzhT9136zLrXyxji2AYBuAmsv+JM7CUgbqLhrH2fvzDfAvn7Cux0k6yMcMv82MN5i1w1+IRaOfF6KyBV0sF9F4LY4i8cPW6qbf6HeTioLm8tJm9K4DQIebO9dDjZr4hehBjOKp+Zl/P58BGQ2DwxlRQnNM4upe1GLcV30K9PDn4SUVrhx5zcLds+/iQ9mPaS4Lu5f7Fw6K+JAdvdO+cEJwS7ND6/cbTzKjuGcGmX3xdAR0JLN5Ekv1OJmVY19N0I/ow/sT0PXSfvRKXrZMvyqwGfTEb/gAMeWoUYjV1XvdE90sw9vinjQNzkdh00S7ln8wg/32R1VSwwDQOJiuoQhLxKL46X3XJpr9t5ADRdDpylXQsWCtmC/asaW8JQww7mb1PUyQL/8buXGKuoCOwkIlaLnhyWVjso8f1V6k6T2sXtbEt1CNk0Ll8boYbD3AVwMpMXeyTZdXu7YYkb/zWcBzsdKcAzdVcKgeV80lhmMX5QI/ZzzU/6VzsyGgbH8YwCRp6pwszclEnMLkWBbuGfoPWT6WmHE/TLsajwoL/el9UNm83m41d9kBI8+/sKYUATh+y7DnxMEV33fUCj6Pw/1jkJURuV0AybrZ6I830LZrYGqUakt81bF0SEqkIaXwVNC1X+oBdrY/RlRS3AX6uuQBCQzNQsvm5I4vBAjhuuSffSMNujaWiILbJV9a277vQD3rYoJW+tLt8+x9mjP25WxD1F8yM+kg1d9xSJtDRBCHdgRbqM8WCewevBkpHOvfQ+dkHSTGzUcvAAWmrXUs5E3
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
    type: Opaque
