---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: pocket-id
spec:
  encryptedData:
    ENCRYPTION_KEY: AgCKvYRZJqyUTgNwYQk9KUeMegQC4dw3wFiNKlogRrlu+ENcAHcVHfidZ9mPu6P3XZPsORhpv+b1IB/GaInpKdgyOJdoUxK4F0oQ1Ou+BczTtc9F7DlmpgYcHbT+ZFqymtpgnYqsfrHjGJ1jA0Yax+xlTc+sKTpMvLWjUY7ja3drUNqAE7Qto6+lqsUaMOV6IPnr1Uxpo1MYsEZ7UdB4WiMAkK+n2KZdLfr0V1xt8QzWjPQ0U2lQvgmlXsXHdUDzhfxo7EHO9VKEpH8nWD2pIzL2FwwgJVD1RJJoN+agSeAsOjyAr0zWnfYIsdCfWzx8JLp8oesLQfr42ggqyewzdI+y+d0toAJ7QYf+xp3ZftOssModuv1NIpu32K2f5T0Q+I0V7wPaVuRP3Vhok3FZA0JnfFYnWV8jHDbqeyXqs1JW/l6L9HoQMIkUmcY9fY2DyFk9+gxSmatY4KsJaImMBNOw1c9KfBV4wL6pgaQP/6SOHcGkqqsVdmj97whYU881VNOcpZ+FAMp+rBTzOne6H9f/eNQIHr1EXcAIiz4zG5jZr6P2d2xvFwF4P0LeZH84pagWKmuf7Miana/xXM/1KEtXfLsDU4b0aLIWU7LTQiN9kSTwp3safWCT8SJr/+vO36hqRAd+m5MIl797nJFdotli63C47KtPMb8JxqHWBzE10nqmku/gIijgefEH5D6KXzb/xF9kPVvIDd8z9ZtFU8+h9Bs3OsIyip4rHhZ4Ijrr12yWlwkufnGCB8euWw==
    MAXMIND_LICENSE_KEY: AgByVbYvDQM7+YH9UwvcihnQWnhHaCJTr1qNLUxxJrfeARdkcbsRNRANStRXrL78Ez0WcJOsMla9lpvdfF7RcAhQUUQf1sQG1E89hANzU3yOPhMtQTenI/rRzODL2je8wxA1/ev1B4A9gu1tW18mhPfIXoe+2S1i7cOhisnWUEDWtCmxZ8XbegCE1qpW5/rVSJRBl4juuNeEEeUF/S4B0l168tgpcNBWy5SJk7j3L07CP7A+lOsjJfwCQFb9K1f9rH8mA5wKU3Snbm7URoTpO8Hqs7k8By4BFkBk7Zq7UQkoUTXbnlvhCpSdZfnFP//5L3oCZq6l7YxWLRrSUL0Erjl4UHOGxe4EyodqxncWS0VMg2Aw6li3gh6pECZ5yS1P1IzErYmCcVU2gY/phZn+R1fRe4IQIl5PDErVqj5h/frebrR2xy0Ouu+unHeIymu8l/VyWux1DB1E/T7uE8pYlqr+SGJCGgp/cOzxnd4rOE82AERNveBiXB6aeLDtzqJcQQgHe0UIOPmWgIWzXQVV5zrVGcAKv+rcpM6oXIh/UdPQlUCCRksYx/GWEED74o0g1iEiEI/ZXroxSiB+W8u51lr3i7NrjsBtFKsVXVV6BtMEtsJLKK66wDERAFS1RaG0FssujJmntQKPicMVR8PKcxwyLsj8rMUy0T1K966e0BdmYlZU3Ubbz3KZvahvMc7oMfLUQH0KTa7MzNdOVb9/FyO2sZjH1JFjaDCjqFHQFkbF4YHnQ/L6/EepBQ==
  template:
    metadata:
      name: pocket-id-secrets
      namespace: pocket-id
    type: Opaque
