apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:14
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: TAILNET_NAME
              valueFrom:
                secretKeyRef:
                  name: tailscale-config
                  key: tailnet-name
            - name: FORGEJO__database__DB_TYPE
              value: "postgres"
            - name: FORGEJO__database__HOST
              value: "forgejo-db-rw:5432"
            - name: FORGEJO__database__NAME
              value: "forgejo"
            - name: FORGEJO__database__USER
              valueFrom:
                secretKeyRef:
                  name: forgejo-db-creds
                  key: username
            - name: FORGEJO__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: forgejo-db-creds
                  key: password
            - name: FORGEJO__database__SSL_MODE
              value: "disable"
            - name: FORGEJO__server__DOMAIN
              value: "git.$(TAILNET_NAME)"
            - name: FORGEJO__server__ROOT_URL
              value: "https://git.$(TAILNET_NAME)/"
            - name: FORGEJO__actions__ENABLED
              value: "true"
            - name: FORGEJO__auth__OAUTH2_ENABLED
              value: "true"
            - name: FORGEJO__auth__OAUTH2_CLIENT_ID
              value: "forgejo"
            - name: FORGEJO__auth__OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: forgejo-oidc-secret
                  key: client-secret
            - name: FORGEJO__auth__OAUTH2_ISSUER_URL
              value: "https://auth.tailf95ba8.ts.net"
            - name: FORGEJO__auth__OAUTH2_ACCOUNT_LINKING
              value: "auto"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: forgejo-data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: forgejo-data
          persistentVolumeClaim:
            claimName: forgejo-data
