---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-oidc-secret
  namespace: forgejo
spec:
  encryptedData:
    client-secret: AgBv5vUABVjQDKImX1bVp4lbyGjp2Wfey9G4T/hEiRuACpIwXyeOfnMC/FVTh9q0ZqkYw7e2GnftSjb0NnpavhRlCgi9Mps6zRcTNfP2l8n4A1bPkU/lXeqZUfC2ezHO34GIXyyEzeW5vYhzaTOh4CJaeO6l+BElRfAXuhSNaWSvO8BNSD+XkYFgAyfXe2vq0JmE6Ngg5AXwE+FzHP6pvHMqD96BWzpVs8qzfdXQ2q+7rUVaiUTmrC83c124nlePsbscEUAgkYk4j+bgtDBOMSEVnwflmQBdfdx+umVmluDBkJOm3MMLfW/bRy4C661HLB99IeMEzgBbyLipCB09oCV1vco2kq1NPvMQHKXn3XKfd7lRqcgvI/su3zA9Tgt5KF9PH2pDitFULOOW8Gc4Kq2FKD6scgI6sau5u9MNWpHZvgvk3wGkfE9ubI4h+X3sWNUi6bpJ+syGCeR0AtOXh/cHLeLYB7MpD8RT+EEc+rqXbIqi4IP/LYUQNUOoquGdzIbA07qkTQJQbp1Klk3F/mx/f5DnSWkf9uZ/rUUd5lzvhxxZnRdoMe276SLbcz/7546eTgLpjGlTwaEz5gKvfRhBmxiqsHJONGcnbEo9tXn/iDrDkvlRlf7PFz738pl5kf5MKlcr0LiYYWp6HAmnH9OI6X7ii5Fg1aDpMU2N4Lm84DMcKll+JmTi1HGEy6TzwyL6M9dwTj3JDrWa1FeEWwelUWr/WJG/Df/KgFVrssNjbA==
  template:
    metadata:
      name: forgejo-oidc-secret
      namespace: forgejo
    type: Opaque
