---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-creds
  namespace: forgejo
spec:
  encryptedData:
    password: AgB6dSVeP1UEt9KKmoxmiupNAmHboeJjEr5ZFPF5yrFQC1Tg9f9TyPWkg/01rC+RIjYNtcyo7gYwU1rMHq/6Dh2wn4BfEd64x0Z2dVIkWt5rwePYA1AZyGXLPRlKn6lZ8oo8xz5jzSaQzTbX9Kxb1csjppzHe+PzzQjYhF7rizOcD4zCdvnMqn6O73In3nHDPHtWY/17P+7iEUeN1VkucSHMVtcusE61PQuy7AsuuV9NLw5ilAun+Qs8/YlBPczPr7DuUXjASTnQKiLzAn0r6mhSOxp6/nFEukg5rZsoiSkgmGpgJTG0cCpOAPpPz4sxmRUVANEiDP2NEoA0d8ImbusTuNOtooBXFthSGpVIGjGwvxvqYLAQ92pud4c+jw3DRA1PpGwACCv9sLJTzuiY+c4xfKpExsP1OcVSeZJc21wSLmaA37HDgC+7Aw98gIjTHvMgLpM1PWuxrtAhe50LCbUo8Oxa/waEpp34lT2qSAWXiNvh/4Si27kcfTsR+J991OuozWE6YyRfIMoHqPL99syUaR2iRza0Q1uj+DFfEvdI92FtGvclivLA+lFK25+93azz44sQCth5H/vK6CBKyXRO18PiT24lmjyYXrHKFmvV/EhA63C9jK31SPfO8ojXCQyl/XJdAl7ChRZhG7HFz343wd8qqqag/VW9V9NKTOjTe9ktHyLfN4kQEw8xPl7S30r+/AuP8BBp/cVUbaxNpw==
    username: AgAGajIn8yg402lW3BfQk3J2lw0cfdFR4wHt2k/M7dGXZEMmb0VHmjoVnRNdj/icV8DC5Y1yzAP+9juIHwiy7b5dTp4pu1peICpZvtwPmL+qX4ojJNKXVUJFbWqPQCj9mBjw/Jon0YCjQQEpE+yQPPuzljain6dSVZMOHChT+V3KnT+/RYlu7twoY0bcnLju+j2S54PTVsism7teW+V4Eb/005mpkzN/0B5edbhwnZKKi6l28pZv0OY9nIz/OmvtLSvpNXhFejJ20O2KZOQfF55XwloQoqYm5Dk8Z7AcNFExGqsusr3qdYO9xp08WE2ZpKjhCGdk2etwIx3az7aWajw1yIyJL/evZT9p49UbgsBAfMqCs/Wi+MpypJqLhQH/Dr+ui1rUmD8XCVm67LWKoUZgMHaOsnza/J1fz5H4E+a460983jXdLs8bKguEl69asJGl5xyInZmN9ixTVzmXXWv/w2Vvib8LseyqJjRp/I/hHRGG6Axg3OmbMlzwTyz/JEr64OOGSA3gYdqTXigLKi6LSHK/uGoZNTHdFGLzOlahaqja6JCUApmHTihu8h1rvBYTo1wsXn1/HCE9Q3hxR9vD0EA/YwU34QDhHbWW+X9NdP7y6p9tlyUejypfApP31BHwWLV800rXP+sX7USJy0mCPKMj2tmDyhpW3KqYqpPr8NVzIoRWKw3WP+eBzPSNzKl3MpdzllvP
  template:
    metadata:
      name: forgejo-db-creds
      namespace: forgejo
    type: Opaque
