---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-config
  namespace: forgejo
spec:
  encryptedData:
    tailnet-name: AgAFJUYQ0bIPbJWRuKQoOk5n9tHxEWpAVn+fK6SpWsKJMAeDif2FZylX/HFuVk1fLvInt+EOH34K5o31W24/uRBovoYgdOlax01ls4tb6kx+sSas/TDjUK4YENGVwPIPrcZ7m4Sb/D7zoiG4CVg3Wh3dx+DB5Zjnlm/fTkrqC0ZMOd+uWqKaswrXKWXugkjkyA9F2N+4geDZ/rBiJJS3stiI0i/VQ7V7P8u5mpw+WXZDmjlv6hjcnHoT8BbHhk+/Te6/kx7v+MwvKsjxMkHrlbdgkdxBzWXi1Vbyzkgyb7wvXCR9IIXPYGp7OSht/KQMIf73VGWwSwt93q5KrZiEKMhPVh55u88sl+Gtz+S5LKYtl3gCuTfl7TtznrbZpg6hJdOaZkUXt6/JRxbSdX837ujY8q1DurBclydMzpmSePbtamO6wV6zM5VpjnHSRlPuqot0uOwW0VhRymWvbSkWAAEn4tDu/fZc63fgvaVezP92vOIYYM80u4cctaPgYkYZVu82dctalJzrYHJKw4hCO1oMN2AJzDPdYS6cr7lrbVHLF21LORsW3ozbvLQrd5yrpEZNoC8unxunF28tZBi9AHCFbe2pj97YbNEbGZTlhEsa76YkFYfFfYribg+uFmDBENEYN8Y09PMpdKyDDHYwJeGY5EVGJQ288zorkP8cOI10q7JJru9nv+vaQEG4qzs6B71BH3696ss/Yda8+bjbMmmNcg==
  template:
    metadata:
      name: tailscale-config
      namespace: forgejo
    type: Opaque
