apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: vllm/vllm-openai-rocm
    newTag: gemma4

configMapGenerator:
  - name: vllm-model
    namespace: vllm
    files:
      - serve.sh
