apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: default
  namespace: kube-system
spec:
  devicePlugin:
    devicePluginTolerations:
      - key: gpu
        value: amd
        effect: NoSchedule
    nodeLabellerTolerations:
      - key: gpu
        value: amd
        effect: NoSchedule
