apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-db
  namespace: coder
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  storage:
    size: 10Gi
    storageClass: longhorn

  monitoring:
    enablePodMonitor: true

  managed:
    roles:
      - name: coder
        passwordSecret:
          name: coder-db-url

  bootstrap:
    initdb:
      database: coder
      owner: coder
      secret:
        name: coder-db-url
