---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-oidc-secret
  namespace: coder
spec:
  encryptedData:
    client-id: AgAo2nifQ8ojsahiup4yZr5Jmgf4eGTUpScV7x8PXu8ZYOHfhDPcjByfYjWES6ePnoaq/htAJXjSboVqyn5HC5W8AyCG+w4JKCEreEDTnHfCNWAeMtFvxCJOeFHPLdYZrX/JInWUy0JYL/+DzERNxfcsglRsZC2Ql0SC3ZuytQ0nAM2mtXTGiMZi2RNFA7mvNPU4M07lPEZxJIEYSiwpCPlSxKBNND+XgJp+A4oQ8zSpmavM65Z5G9+KslbUpZCqlOyIR2uRiJyvXz1yIXPX/jTmnfb0djiOW+GuXRZzPE3p7xXHvkITnlrkyU73u4/7iSpRKbFRMX3jVs0jEBXDc8LNWRsOOke7KOwUjWzyAekU+Om4j8VPBnhcvJ8QjM90aVsy9m4niN+k33PMIpY8yXbfLUfURB+LCL+0RHu50tWbTAC9M7vWk8oztMsN5UW2enOL/9aEvt95H7sFyq4Iodl7pkUDaHjipws6sis3MFABgTMJgsq6o0ypED7yq3E40uLByI/konD2SYZ/fKgcwseSv6X4OXsCpK4kfH1ZXWCRJn+d1WvtVrDqC7RvOh5sNtqCFP9htzvryIi6RvfrouYBo/qgKJQM1Ukt2BOGzPJCn6TPU3kCiQOYmxm5qdSjVgWyoE7Z3wOReLtvTZErQI1KKFBbdQ8BEvzcC93ygpLNR1wUYbezt+XQM1qrUyExk1teuHfq5w8JpirXbp3DIRs2OyptAROgQMBNoUh1vWkYYznW1wU=
    client-secret: AgB/UeT9RMJt98bwxjnx/Gsjx1r52aJMStDTetfgUMSxkEbOUDgRhOeOYp2lrBZ01Fghtsm57+SaSiCGNLxyQkw/HxVfiYCLD76Eile6SFJmp+MgqiW5qAhfVmsVoHdP3lu/mZf8e58P7ZtLg/sL4FGF6c58uhS+YY8msuNzRvFlZ9W0c2tTUekFA3fE+/0jWBZYNhJ2MZZrKUIh1lHCjl1r48D9bjLFMczEULsssS0nFfjSZd+V8nMWkP+0r0G1TCKGXtZZjqzJD6nmcDUCdkO/W2jyPJdO+z3cLEpJwU3cWJDOKCw8Wr8ZI43TF/Gjyp+vVO9WQyc+k5jUHXfO7tJU3/qgWjSP2NZuetxLFqZOztWgeeVg6SSXVNw7NU4PAb/3bKkMY+b1Ihg7Ha5jLL+/l/+tZalPM+WAAb939poha/XjQi1BEkB7B3xlLP0ZMrl+kZm/hMKRjprlSaXMj0CbW5+qFbz2YbCc9RvZsxEgey5HdVjcC+mf5mSLKn3HB5yeYnNucVglDgYbVnwT3Q4vZjd//0947aHh3Op4Xxm5ZZaN8nrUPtFxybi9RR+2fxYx/P2uw97CGad+QhXyw9GqaAkZxArenDk0jdlrHfSDTFteHLeh/BpucdFuAI4zdmXu5fmwKZo20CPoVMd61N/f8IMfcLz9+mjZNR0aSHd+vzg1IBfILpCbMoLSTmIZV3AZIR6qjzFaErtpdIV9r2iYvGprli3PNEmsMp/MV4S6YA==
  template:
    metadata:
      name: coder-oidc-secret
      namespace: coder
    type: Opaque
