---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-oidc-secret
  namespace: coder
spec:
  encryptedData:
    password: AgCKLXC7busU6WkxksvH145i1Ihwil9D5EqoPx+NmkNP6OKI5lLzvYglRbFV65i2YbMyEBYDjMYMyo3RS53zQWpZVfRkyt1qknAaoyHWblod4EtSmQ2/rVmr0g/YGQD3jIO0Mmey96I4I/UxZvM/ELyKA3Fgl/Dgf5dtRcYEBQLLN0JHGF1XHB6exu1rLanRhIGKzGZwa3p+MjJMRAtmTJYmhjT2iaJNz9izDElhTkiUE0cPH2uyLFzvsO1ZE4IfovalpoCKHX+iGu4SUJfQgx+x8Y3IuY6YhcHjSYX06SwfK1HjANcTtopahXBPkN7oez+zJMFRIVQgvAWzW8Sd7WbYXOF0V93mcOEZ+S214shyJoByNdhQpKHWSJZXRyAWeb9AmsE0P7ZyjseNmf4O+Lg16nFbKpf72Q0T5095w4ioZWAhA1sKjc7BA80R9zjUDsIhLBqk+LsOehVEWGF+eht03A9uauYar7Mf2LyiHcCurMiT79fesJ0IKcRQWQ6utHL3Gg7Gud15g6TccXo6UaLcqFkrJi1kGuFbBinFKalvNkTTm7Y6iD3bSCYI0vOU176nCmFstI1ENF9czNk+mA4oRC64TD/EN0fLmgRiwnNnqKeGSLZbr+6T2P8CyirRoaR85KAYUdU9AlBWIQrGS+a+8V/OLYqZE7v7yrs5l3SvvBWB52yly09e0kUPbl75J0XSlcixLAOVT7jEuIbAHNs38+sLZy4H1S6K+YU4O5YO1g==
    username: AgBqS4ZbWwLGV413RjRZ4UGaGGQnUnP7hdR8xEpe0AcwJ4sy1BVL9aPg3/QjQhmur8/f3WrklmMF6c3SgtiStbxdGPx7QI7tcNiV4bVDGsbtq1TIdcabw5ULX/gvHXmGEbPT+SYZhDv/mESdV9P8YEW2A7wD8d8alPhRvhqsbex12D1zjhqc9IzTdaovr76UCpbxLGPubRd5OjKakwzUsI1vjTtrePElI2ZRyHOOnN9dC5pEqwdT1TpqGtow+U5eZKgbQs5sba/82zvTBheRNA9r93I4hflKgycenQyNj5+TGbirfH4F0h1Y1igdp9kJBk+EMe/t0ktX8SAAZAhdA1Mf4NT1UEq6cIFDs/EhpCIevf2lG02xDfYRl4tkdTd3egtciJIbWQd6yQo688GdM7+o1m4I5HBQq8TGt0QNp7/dB4Babh1N1PBR2wG8iNWFARyXdYOig2yELQtdLVVxgvmr1rpHupGhmLZaNTkCXceFC/SBpFn2T3hZpm6ikosSLEK47sRWOTuKuFjsewGioSk3yYqepjnM++9w7kFJcskg0FJjBEBQKVGbnDK3T9nxfHePhFjRPT9xZ0oC0/D0CKj6mq/vqY5E8ycNS7zbVncdgk2PnA9LEnxt/l8yyWtLj4vZqlfL/yttXuSMdpjRc8WrOZCA1GEdDeDixc254ZA4OEKf9Bi7500Bi25LH6JlnH82SQXgbXKdNwzjc3NR5LpEnMiBQFxA1PUAtGTIkCowBYLfdyg=
  template:
    metadata:
      name: coder-oidc-secret
      namespace: coder
    type: Opaque
