coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      value: "postgres://coder@coder-db-rw.coder.svc.cluster.local:5432/coder?sslmode=disable"
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: password
    - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
      value: "false"
    - name: CODER_ACCESS_URL
      value: "https://coder.tailf95ba8.ts.net"
  service:
    type: ClusterIP
  ingress:
    enable: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/hostname: coder
    tls:
      enable: true
