---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  encryptedData:
    HF_TOKEN: AgBVZgx0ucF7NPy0yCQHo/ytwM2IMVVj19o3xqLSHhuqxVx8vBloxHMYh+eaLqvm4CD9wkW3DOt7Et6+apOwnrW5fY/fyt/E+qzvrXsDB9dOyO58mPTNOxDQo9k0e5RazzbqM6flYQc+x/F/UjwsxKwnUl1gbu045BvAd4fzD7KXHhfocjMw/Hpae8XPdpZ+76tzdFfS7W/yTloDUCXC//dA+l7ukH8SuBgo2+ROwoiSWZuWkudVOhvkpNCKSDSCKvAhajCj7TbynI2+rH2uRaRmL2GtIsOu9ASw6l0Jwe2z4GEE1vitx8OeSXyrkkdw1GUKjrgVlS7y+plIXqOlSiY/hhnUfnfbuTB3ldE5VEo7aUVbEi/yws2ZMdu9+WmGu0yUi6nBrmWUBbihpjQOE3xskhUjVbvCcAEcnaQmpn7jFajGE+rgLKVQbJReU/+cWmI30jEmQp/+U8Oa6dmNeozZrFXYyoMyKe+8GPvh7LdUndKjVaQj8TEZJVKPNul+X9T86rIrlptyNjyPe0dplVHQq6jTmGnEQHnMxnnUP1QL2rEt9OY5WAxS66w1SUFpoDc9p7bLKsfI82t8h1nTc25mbEKph3zZLmr16hVwOh3h4CIfneU6e/xvwLFmHlTjvdazE86wUvE9zJTHbuFaAOKbHfpzUzu4zrKQ2aDB9Cc3sdAj93qSKtrZeIm6wOuUgybhCWLNY3Iwiv1zxHitSsbXSGCIKKe1SdWyGHvrvKl4FvtXnzbg
    OAUTH_CLIENT_SECRET: AgBQBSeo3HK24ieN9SYDAFYM7p2NkThlss+bCWJDEblW11bZdnes5o8eWxnX8SqO6FsGfWYmwWOhCd9fXFsx2GobmhHtrzvJEVM9A/0pkAke66GeqZXRDd5ZHgzF/5yAtF3i47OV+HYFrCMBDHLCnZER1nHVi8O3Qg3dNYKGMxiu+lfFo6RldhbnMa2C1zd34Nkv1+MwQZcfZ/tIklFzL0JN9Elan0VzmZyhy7oMRo6+avZY84MPj9BFC1wxU6lqZZ0yli9wDLhg1UHqreTwSk6yOrir8bLgpkWI+8CY3Re4hUMVjFEuXkMrNEVWvC01JN8bIfa0lqbayov6K55Mo4unEF6zffT9X+sKKezTLDtJJGkbTAwS1d1DwqRyGnBvcgaAe9CEb0YKaLd+WBM+FbtM3dH0wCNd89UOxu6o2G7gpLrX6YXeth56S32M2N0ItzUkkU2YABEmpoOU0ksPUHW1eRzjZvz3Aa8LSH5ALkOBzJJ/h1gEjbLUIkUU9kCxusS8jv3OIx/dOZpvDZMu1KFCYh5wUXIHvTjwfM4WAPC9Zpm2kKR8KDNIhG+nZWUuWb3h+MPay8f6N1SlHsHPhIO9lboN5bzYjPmNGshcf8SnQkNCc09/kL+nSzthyMDkctpr5JrjfOhrKE02+KdC9PJ2fH+xUpGI3SEy06aabiZEqyAB410z0z7ERrE84Gx0foRbOoo8EkjiuhmbXk9Iq41SkLeQSPo+gHGYkk25w2gvzg==
  template:
    metadata:
      name: open-webui-secrets
      namespace: open-webui
    type: Opaque
