apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argo
  oidc.config: |
    name: Authentik
    issuer: https://sso.tailf95ba8.ts.net/application/o/argo/
    clientID: jwFNTRJYgNVaYBcxRggIw4XZiNqwJEklXpbHxzZa
    clientSecret: $argocd-authentik-sso:client-secret
    requestedScopes: ["openid", "profile", "email", "groups"]
