apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argo.tailf95ba8.ts.net
  server.insecure: "true"
  oidc.config: |
    name: Pocket-ID
    issuer: https://auth.tailf95ba8.ts.net
    clientID: 59cca452-5fc4-47bf-8756-f9cf2fefd44b
    clientSecret: $argocd-oidc-secret:clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    config:
      insecureSkipVerify: true
