---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBK7bXeDq7NGces0iroRzD48dHOIu33sD4B0dwq55sv+rFa6mrCqhBpTyFHHJwB+BFy7sC+627LX+EiuaQgTCXhgxK/0tj7iS1L+qMeAjWj1jNKCmsIVvjV57kf2SUU2s2Crv8d3ykm4YQBiIdwaSGlQNTqhvbYMdoiBhmuvxICXwU/BsPZIvm7EhwacJ55uOvVXhzRkopHApY0lcaH94AQfV7QObNcTMYl3ewpvB9V1U5ISFkKi802JXb+C5kCe+N231ZRpW2fliU/DaDQbmzHrLx6YylmnDVjBgCOdKqlmLxssTtRhCJfU+/7S9HVrSUi69F8StF32VSTBL3Svx0J2Qgroo1Fi3ywK/qr5Ud4gKpQkavKp/BvNX0Da9iwYWhM6u3sgmLfZSTFm8I7jQAsw2UPAOCRBwZecCh7ZOLbIOmPjSPp1ZXXHmCFC7OBHHNkeRgc83we2U5J5cs4ruNx2yS7vORrYoVYdzrEZdC9DWPYhUX/fHsdemFko6xQQxM49M0PSEtKUYO22N4K5jd0XNz0zG19xi1/yfYJBLETYOm42bIdSeHMK7TM3gf5lRgvlD6msrcMMzTbegKWN8WpcqV7veVc5wY57Tmmas3jG7ijmwqBz7shBa3lExJa4Nz/D3FCBmyVVWQlyOL+RBxSGqFpXK9qKAW3DZTI7KL/I+nDZ457wHmgoLGosI4NpRZgKcDWWyEP0t0db7BQ6FyypJx72DSF1GG1MmHBxpcGkg==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque
